-d C:\Gowin\Gesture_Recognition\impl\gwsynthesis\gesture_recognition.vg
-p GW1N-1P5C-QFN48XF-7
-pn GW1N-UV1P5QN48XFC7/I6
-cst C:\Gowin\Gesture_Recognition\src\gesture.cst
-cfg C:\Gowin\Gesture_Recognition\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
